/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum BulkUpdateConfigStoreItemOp {
    Create = "create",
    Update = "update",
    Delete = "delete",
    Upsert = "upsert",
}

export class BulkUpdateConfigStoreItem extends SpeakeasyBase {
    /**
     * Item key, maximum 256 characters.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "item_key" })
    itemKey?: string;

    /**
     * Item value, maximum 8000 characters.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "item_value" })
    itemValue?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "op" })
    op?: BulkUpdateConfigStoreItemOp;
}
