/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

/**
 * If set, will cause vcl_fetch to terminate after processing this rule with the return state specified. If not set, other configuration logic in vcl_fetch with a lower priority will run after this rule.
 *
 * @remarks
 *
 */
export enum Action {
    Pass = "pass",
    Cache = "cache",
    Restart = "restart",
}

export class CacheSetting extends SpeakeasyBase {
    /**
     * If set, will cause vcl_fetch to terminate after processing this rule with the return state specified. If not set, other configuration logic in vcl_fetch with a lower priority will run after this rule.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata({ data: "form, name=action" })
    action?: Action;

    /**
     * Name of the cache condition controlling when this configuration applies.
     */
    @SpeakeasyMetadata({ data: "form, name=cache_condition" })
    cacheCondition?: string;

    /**
     * Name for the cache settings object.
     */
    @SpeakeasyMetadata({ data: "form, name=name" })
    name?: string;

    /**
     * Maximum time in seconds to continue to use a stale version of the object if future requests to your backend server fail (also known as 'stale if error').
     */
    @SpeakeasyMetadata({ data: "form, name=stale_ttl" })
    staleTtl?: number;

    /**
     * Maximum time to consider the object fresh in the cache (the cache 'time to live').
     */
    @SpeakeasyMetadata({ data: "form, name=ttl" })
    ttl?: number;
}
