/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TypeTlsDomain } from "./typetlsdomain";
import { Expose } from "class-transformer";

export class RelationshipMemberTlsDomain extends SpeakeasyBase {
    /**
     * The domain name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Resource type
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: TypeTlsDomain;
}
