/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class TlsPrivateKeyResponseAttributes extends SpeakeasyBase {
    /**
     * Date and time in ISO 8601 format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    createdAt?: Date;

    /**
     * Date and time in ISO 8601 format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deleted_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    deletedAt?: Date;

    /**
     * The key length used to generate the private key.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "key_length" })
    keyLength?: number;

    /**
     * The algorithm used to generate the private key. Must be `RSA`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "key_type" })
    keyType?: string;

    /**
     * A customizable name for your private key.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Useful for safely identifying the key.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "public_key_sha1" })
    publicKeySha1?: string;

    /**
     * A recommendation from Fastly to replace this private key and all associated certificates.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "replace" })
    replace?: boolean;

    /**
     * Date and time in ISO 8601 format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updatedAt?: Date;
}
