/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class ConfigStore extends SpeakeasyBase {
    /**
     * The name of the config store.
     */
    @SpeakeasyMetadata({ data: "form, name=name" })
    name?: string;
}
