/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class DiffResponse extends SpeakeasyBase {
    /**
     * The differences between two specified service versions. Returns the full config if the version configurations are identical.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "diff" })
    diff?: string;

    /**
     * The format the diff is being returned in (`text`, `html` or `html_simple`).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "format" })
    format?: string;

    /**
     * The version number being diffed from.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "from" })
    from?: number;

    /**
     * The version number being diffed to.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "to" })
    to?: number;
}
