/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Include related objects. Optional.
 */
export enum FirewallInclude {
    WafFirewallVersions = "waf_firewall_versions",
}
