/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import {
    RelationshipMemberWafFirewallVersion,
    RelationshipMemberWafFirewallVersionInput,
} from "./relationshipmemberwaffirewallversion";
import { Expose, Type } from "class-transformer";

export class RelationshipWafFirewallVersionWafFirewallVersion extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: RelationshipMemberWafFirewallVersion })
    @Expose({ name: "data" })
    @Type(() => RelationshipMemberWafFirewallVersion)
    data?: RelationshipMemberWafFirewallVersion[];
}

export class RelationshipWafFirewallVersion extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "waf_firewall_version" })
    @Type(() => RelationshipWafFirewallVersionWafFirewallVersion)
    wafFirewallVersion?: RelationshipWafFirewallVersionWafFirewallVersion;
}

export class RelationshipWafFirewallVersionWafFirewallVersionInput extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: RelationshipMemberWafFirewallVersionInput })
    @Expose({ name: "data" })
    @Type(() => RelationshipMemberWafFirewallVersionInput)
    data?: RelationshipMemberWafFirewallVersionInput[];
}

export class RelationshipWafFirewallVersionInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "waf_firewall_version" })
    @Type(() => RelationshipWafFirewallVersionWafFirewallVersionInput)
    wafFirewallVersion?: RelationshipWafFirewallVersionWafFirewallVersionInput;
}
