/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * OK
 */
export class ServerResponse extends SpeakeasyBase {
    /**
     * A hostname, IPv4, or IPv6 address for the server. Required.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: string;

    /**
     * A freeform descriptive note.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "comment" })
    comment?: string;

    /**
     * Date and time in ISO 8601 format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    createdAt?: Date;

    /**
     * Date and time in ISO 8601 format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deleted_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    deletedAt?: Date;

    /**
     * Allows servers to be enabled and disabled in a pool.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "disabled" })
    disabled?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Maximum number of connections. If the value is `0`, it inherits the value from pool's `max_conn_default`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "max_conn" })
    maxConn?: number;

    /**
     * The hostname to override the Host header. Defaults to `null` meaning no override of the Host header if not set. This setting can also be added to a Pool definition. However, the server setting will override the Pool setting.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "override_host" })
    overrideHost?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "pool_id" })
    poolId?: string;

    /**
     * Port number. Setting port `443` does not force TLS. Set `use_tls` in pool to force TLS.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "port" })
    port?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "service_id" })
    serviceId?: string;

    /**
     * Date and time in ISO 8601 format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updatedAt?: Date;

    /**
     * Weight (`1-100`) used to load balance this server against others.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "weight" })
    weight?: number;
}
