/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ServiceInvitationDataInput } from "./serviceinvitationdata";
import { Expose, Type } from "class-transformer";

export class ServiceInvitationInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => ServiceInvitationDataInput)
    data?: ServiceInvitationDataInput;
}
