/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ServiceAuthorizationResponseData } from "./serviceauthorizationresponsedata";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class ServiceAuthorizationResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => ServiceAuthorizationResponseData)
    data?: ServiceAuthorizationResponseData;
}
