/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RelationshipsForStarInput } from "./relationshipsforstar";
import { TypeStar } from "./typestar";
import { Expose, Type } from "class-transformer";

export class StarDataInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "relationships" })
    @Type(() => RelationshipsForStarInput)
    relationships?: RelationshipsForStarInput;

    /**
     * Resource type
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: TypeStar;
}

export class StarInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => StarDataInput)
    data?: StarDataInput;
}
