/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Timestamps } from "./timestamps";
import { Expose, Type } from "class-transformer";

export class StarResponseData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "attributes" })
    @Type(() => Timestamps)
    attributes?: Timestamps;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}

/**
 * OK
 */
export class StarResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => StarResponseData)
    data?: StarResponseData;
}
