/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class TlsConfigurationResponseAttributes extends SpeakeasyBase {
    /**
     * Signifies whether the configuration is used for Platform TLS or not.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "bulk" })
    bulk?: boolean;

    /**
     * Date and time in ISO 8601 format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    createdAt?: Date;

    /**
     * Signifies whether or not Fastly will use this configuration as a default when creating a new [TLS Activation](/reference/api/tls/custom-certs/activations/).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "default" })
    default?: boolean;

    /**
     * Date and time in ISO 8601 format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deleted_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    deletedAt?: Date;

    /**
     * HTTP protocols available on your configuration.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "http_protocols" })
    httpProtocols?: string[];

    /**
     * TLS protocols available on your configuration.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tls_protocols" })
    tlsProtocols?: number[];

    /**
     * Date and time in ISO 8601 format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updatedAt?: Date;
}
