/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RelationshipTlsSubscriptions } from "./relationshiptlssubscriptions";
import { TypeTlsDomain } from "./typetlsdomain";
import { Expose, Type } from "class-transformer";

export class TlsDomainData extends SpeakeasyBase {
    /**
     * The domain name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "relationships" })
    @Type(() => RelationshipTlsSubscriptions)
    relationships?: RelationshipTlsSubscriptions;

    /**
     * Resource type
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: TypeTlsDomain;
}
