/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RelationshipMemberTlsDomainInput } from "./relationshipmembertlsdomain";
import { TypeTlsPrivateKey } from "./typetlsprivatekey";
import { Expose, Type } from "class-transformer";

export class TlsPrivateKeyDataAttributes extends SpeakeasyBase {
    /**
     * The contents of the private key. Must be a PEM-formatted key. Not returned in response body. Required.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "key" })
    key?: string;

    /**
     * A customizable name for your private key. Optional.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class TlsPrivateKeyDataRelationships2TlsDomainsInput extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: RelationshipMemberTlsDomainInput })
    @Expose({ name: "data" })
    @Type(() => RelationshipMemberTlsDomainInput)
    data?: RelationshipMemberTlsDomainInput[];
}

/**
 * All the domains (including wildcard domains) that are listed in any certificate's Subject Alternative Names (SAN) list.
 */
export class TlsPrivateKeyDataRelationships2Input extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "tls_domains" })
    @Type(() => TlsPrivateKeyDataRelationships2TlsDomainsInput)
    tlsDomains?: TlsPrivateKeyDataRelationships2TlsDomainsInput;
}

export class TlsPrivateKeyDataInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "attributes" })
    @Type(() => TlsPrivateKeyDataAttributes)
    attributes?: TlsPrivateKeyDataAttributes;

    @SpeakeasyMetadata()
    @Expose({ name: "relationships" })
    relationships?: any;

    /**
     * Resource type
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: TypeTlsPrivateKey;
}
