/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WafActiveRuleResponseData } from "./wafactiveruleresponsedata";
import { Expose, Type } from "class-transformer";

export class WafActiveRulesResponseLinks extends SpeakeasyBase {
    /**
     * The first page of data.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "first" })
    first?: string;

    /**
     * The last page of data.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last" })
    last?: string;

    /**
     * The next page of data.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    /**
     * The previous page of data.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "prev" })
    prev?: string;
}

export class WafActiveRulesResponseMeta extends SpeakeasyBase {
    /**
     * Current page.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "current_page" })
    currentPage?: number;

    /**
     * Number of records per page.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "per_page" })
    perPage?: number;

    /**
     * Total records in result set.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "record_count" })
    recordCount?: number;

    /**
     * Total pages in result set.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_pages" })
    totalPages?: number;
}

export class WafActiveRulesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: WafActiveRuleResponseData })
    @Expose({ name: "data" })
    @Type(() => WafActiveRuleResponseData)
    data?: WafActiveRuleResponseData[];

    @SpeakeasyMetadata()
    @Expose({ name: "included" })
    included?: any[];

    @SpeakeasyMetadata()
    @Expose({ name: "links" })
    @Type(() => WafActiveRulesResponseLinks)
    links?: WafActiveRulesResponseLinks;

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => WafActiveRulesResponseMeta)
    meta?: WafActiveRulesResponseMeta;
}
