/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as components from "../../../sdk/models/components";
import { classToPlain, Expose, Type } from "class-transformer";

export class Errors extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: components.BillingAddressAttributes })
    @Expose({ name: "candidates" })
    @Type(() => components.BillingAddressAttributes)
    candidates?: components.BillingAddressAttributes[];

    @SpeakeasyMetadata()
    @Expose({ name: "detail" })
    detail: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: number;

    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title: string;

    /**
     * The error type.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: string;
}

/**
 * Could not validate address
 */
export class BillingAddressVerificationErrorResponse extends Error {
    @SpeakeasyMetadata({ elemType: Errors })
    @Expose({ name: "errors" })
    @Type(() => Errors)
    errors?: Errors[];

    constructor(err?: BillingAddressVerificationErrorResponse) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "BillingAddressVerificationErrorResponse";
        Object.setPrototypeOf(this, BillingAddressVerificationErrorResponse.prototype);
    }
}
