/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class DeleteServiceStarRequest extends SpeakeasyBase {
    /**
     * Alphanumeric string identifying a star.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=star_id" })
    starId: string;
}

export class DeleteServiceStarResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
