/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class DeleteTlsKeySecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=apiKey;subtype=header;name=Fastly-Key" })
    token: string;
}

export class DeleteTlsKeyRequest extends SpeakeasyBase {
    /**
     * Alphanumeric string identifying a private Key.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=tls_private_key_id" })
    tlsPrivateKeyId: string;
}

export class DeleteTlsKeyResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
