/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class DeleteGlobalsignEmailChallengeRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "pathParam, style=simple;explode=false;name=globalsign_email_challenge_id",
    })
    globalsignEmailChallengeId: string;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=tls_authorization_id" })
    tlsAuthorizationId: string;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=tls_subscription_id" })
    tlsSubscriptionId: string;
}

export class DeleteGlobalsignEmailChallengeResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
