/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class GetAUserGroupSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=apiKey;subtype=header;name=Fastly-Key" })
    token: string;
}

export class GetAUserGroupRequest extends SpeakeasyBase {
    /**
     * Alphanumeric string identifying the user group.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=user_group_id" })
    userGroupId: string;
}

/**
 * OK
 */
export class GetAUserGroup200ApplicationJSON extends SpeakeasyBase {}

export class GetAUserGroupResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    getAUserGroup200ApplicationJSONObject?: GetAUserGroup200ApplicationJSON;
}
