/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetPoolServerSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=apiKey;subtype=header;name=Fastly-Key" })
    token: string;
}

export class GetPoolServerRequest extends SpeakeasyBase {
    /**
     * Alphanumeric string identifying a Pool.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=pool_id" })
    poolId: string;

    /**
     * Alphanumeric string identifying a Server.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=server_id" })
    serverId: string;

    /**
     * Alphanumeric string identifying the service.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=service_id" })
    serviceId: string;
}

export class GetPoolServerResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    serverResponse?: shared.ServerResponse;
}
