/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";

export class GetRateLimiterRequest extends SpeakeasyBase {
    /**
     * Alphanumeric string identifying the rate limiter.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=rate_limiter_id" })
    rateLimiterId: string;
}

export class GetRateLimiterResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    rateLimiterResponse?: shared.RateLimiterResponse;
}
