/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetServiceStatsRequest extends SpeakeasyBase {
    /**
     * Epoch timestamp. Limits the results returned.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=end_time" })
    endTime?: number;

    /**
     * 2-digit month.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=month" })
    month?: string;

    /**
     * Alphanumeric string identifying the service.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=service_id" })
    serviceId: string;

    /**
     * Epoch timestamp. Limits the results returned.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=start_time" })
    startTime?: number;

    /**
     * 4-digit year.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=year" })
    year?: string;
}

export class GetServiceStatsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    stats?: shared.Stats;
}
