/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

/**
 * OK
 */
export class ListDomainOwnerships200ApplicationVndApiPlusJson extends SpeakeasyBase {
    /**
     * Time-stamp (GMT) when the domain_ownership validation will expire.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expires_at" })
    expiresAt?: string;
}

export class ListDomainOwnershipsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    listDomainOwnerships200ApplicationVndApiPlusJsonObject?: ListDomainOwnerships200ApplicationVndApiPlusJson;
}
