/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class ListUserGroupMembersRequest extends SpeakeasyBase {
    /**
     * Current page.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=page" })
    page?: number;

    /**
     * Number of records per page.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=per_page" })
    perPage?: number;

    /**
     * Alphanumeric string identifying the user group.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=user_group_id" })
    userGroupId: string;
}

/**
 * OK
 */
export class ListUserGroupMembers200ApplicationJSON extends SpeakeasyBase {}

export class ListUserGroupMembersResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    listUserGroupMembers200ApplicationJSONObject?: ListUserGroupMembers200ApplicationJSON;
}
