/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateTlsConfigRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/vnd.api+json" })
    tlsConfigurationInput?: shared.TlsConfigurationInput;

    /**
     * Alphanumeric string identifying a TLS configuration.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=tls_configuration_id" })
    tlsConfigurationId: string;
}

export class UpdateTlsConfigResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    tlsConfigurationResponse?: shared.TlsConfigurationResponse;
}
